#kind: ImageStream
#apiVersion: v1
#metadata:
#  name: "ui"
#spec:
#  tags:
#  - from:
#      kind: DockerImage
#      name: "docker-registry.default.svc:5000/uapi/ui"
#    name: "latest"
#    importPolicy:
#      scheduled: true
---
kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "ui-i"
spec:
  runPolicy: "Serial"
  source:
    git:
      uri: "https://github.com/Dimss/ppro-uapi-ui"
  strategy:
    sourceStrategy:
      from:
        kind: "ImageStreamTag"
        name: "nodejs:latest"
        namespace: openshift
  output:
    to:
      kind: "ImageStreamTag"
      name: "ui:latest"
#    pushSecret:
#      name: "docker-io-new1"