kind: ImageStream
apiVersion: v1
metadata:
  name: "uapiui"
spec:
  tags:
  - from:
      kind: DockerImage
      name: "docker.io/dimssss/uapiui:latest"
    name: "latest"
    importPolicy:
      scheduled: true
---
kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "uapiui"
spec:
  runPolicy: "Serial"
  source:
    git:
      uri: "https://github.com/Dimss/ppro-uapi-ui"
  strategy:
    sourceStrategy:
      from:
        kind: "ImageStreamTag"
        name: "8-RHOAR"
        namespace: openshift
  output:
    to:
      kind: "DockerImage"
      name: "docker.io/dimssss/uapiui:latest"
    pushSecret:
      name: docker-io