---
apiVersion: v1
kind: Service
metadata:
  name: "ui"
spec:
  selector:
    app: "ui"
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 3000
    nodePort: 30080
---
kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: "ui"
  name: "ui"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "ui"
  template:
    metadata:
      labels:
        app: "ui"
    spec:
      containers:
      - name: "ui"
        image: "docker.io/dimssss/uapiui:latest"
        imagePullPolicy: Always
        ports:
          - containerPort: 3000
        env:
        - name: API_URL
          value: "http://K8S_EXTERNAL_NODE_IP:30081"


